version: "3.8"

services:
  db:
    image: postgres:16
    container_name: odoo_db
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo17:
    image: odoo:17.0
    container_name: odoo_app
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    command: >
      odoo
      -d odoo
      --db_user=odoo
      --db_password=odoo
      --db_host=db
      --addons-path=/usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons

volumes:
  odoo-web-data:
  odoo-db-data:
